# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notifications_pb2 as notifications__pb2


class BuyerNotificationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveNotification = channel.unary_unary(
                '/marketplace.BuyerNotifications/ReceiveNotification',
                request_serializer=notifications__pb2.Notification.SerializeToString,
                response_deserializer=notifications__pb2.NotificationAck.FromString,
                )


class BuyerNotificationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveNotification(self, request, context):
        """Sends a notification to a buyer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuyerNotificationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveNotification,
                    request_deserializer=notifications__pb2.Notification.FromString,
                    response_serializer=notifications__pb2.NotificationAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.BuyerNotifications', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BuyerNotifications(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marketplace.BuyerNotifications/ReceiveNotification',
            notifications__pb2.Notification.SerializeToString,
            notifications__pb2.NotificationAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SellerNotificationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveNotification = channel.unary_unary(
                '/marketplace.SellerNotifications/ReceiveNotification',
                request_serializer=notifications__pb2.Notification.SerializeToString,
                response_deserializer=notifications__pb2.NotificationAck.FromString,
                )


class SellerNotificationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveNotification(self, request, context):
        """Sends a notification to a seller
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SellerNotificationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveNotification,
                    request_deserializer=notifications__pb2.Notification.FromString,
                    response_serializer=notifications__pb2.NotificationAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.SellerNotifications', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SellerNotifications(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/marketplace.SellerNotifications/ReceiveNotification',
            notifications__pb2.Notification.SerializeToString,
            notifications__pb2.NotificationAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
