# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13notifications.proto\x12\x0bmarketplace\"\x1f\n\x0cNotification\x12\x0f\n\x07message\x18\x01 \x01(\t\"3\n\x0fNotificationAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2f\n\x12\x42uyerNotifications\x12P\n\x13ReceiveNotification\x12\x19.marketplace.Notification\x1a\x1c.marketplace.NotificationAck\"\x00\x32g\n\x13SellerNotifications\x12P\n\x13ReceiveNotification\x12\x19.marketplace.Notification\x1a\x1c.marketplace.NotificationAck\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifications_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFICATION']._serialized_start=36
  _globals['_NOTIFICATION']._serialized_end=67
  _globals['_NOTIFICATIONACK']._serialized_start=69
  _globals['_NOTIFICATIONACK']._serialized_end=120
  _globals['_BUYERNOTIFICATIONS']._serialized_start=122
  _globals['_BUYERNOTIFICATIONS']._serialized_end=224
  _globals['_SELLERNOTIFICATIONS']._serialized_start=226
  _globals['_SELLERNOTIFICATIONS']._serialized_end=329
# @@protoc_insertion_point(module_scope)
