# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import shopping_pb2 as shopping__pb2


class MarketStub(object):
    """The service definition for the market
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterSeller = channel.unary_unary(
                '/shopping.Market/RegisterSeller',
                request_serializer=shopping__pb2.SellerRegisterRequest.SerializeToString,
                response_deserializer=shopping__pb2.SellerRegisterResponse.FromString,
                )
        self.AddItem = channel.unary_unary(
                '/shopping.Market/AddItem',
                request_serializer=shopping__pb2.AddItemRequest.SerializeToString,
                response_deserializer=shopping__pb2.AddItemResponse.FromString,
                )
        self.UpdateItem = channel.unary_unary(
                '/shopping.Market/UpdateItem',
                request_serializer=shopping__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=shopping__pb2.OperationResponse.FromString,
                )
        self.DeleteItem = channel.unary_unary(
                '/shopping.Market/DeleteItem',
                request_serializer=shopping__pb2.ItemDeleteRequest.SerializeToString,
                response_deserializer=shopping__pb2.OperationResponse.FromString,
                )
        self.ListItems = channel.unary_unary(
                '/shopping.Market/ListItems',
                request_serializer=shopping__pb2.ListItemsRequest.SerializeToString,
                response_deserializer=shopping__pb2.SearchItemsResponse.FromString,
                )
        self.SearchItems = channel.unary_unary(
                '/shopping.Market/SearchItems',
                request_serializer=shopping__pb2.SearchItemsRequest.SerializeToString,
                response_deserializer=shopping__pb2.SearchItemsResponse.FromString,
                )
        self.BuyItem = channel.unary_unary(
                '/shopping.Market/BuyItem',
                request_serializer=shopping__pb2.BuyItemRequest.SerializeToString,
                response_deserializer=shopping__pb2.OperationResponse.FromString,
                )
        self.AddToWishList = channel.unary_unary(
                '/shopping.Market/AddToWishList',
                request_serializer=shopping__pb2.WishListRequest.SerializeToString,
                response_deserializer=shopping__pb2.OperationResponse.FromString,
                )
        self.RateItem = channel.unary_unary(
                '/shopping.Market/RateItem',
                request_serializer=shopping__pb2.RateItemRequest.SerializeToString,
                response_deserializer=shopping__pb2.OperationResponse.FromString,
                )


class MarketServicer(object):
    """The service definition for the market
    """

    def RegisterSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuyItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToWishList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSeller,
                    request_deserializer=shopping__pb2.SellerRegisterRequest.FromString,
                    response_serializer=shopping__pb2.SellerRegisterResponse.SerializeToString,
            ),
            'AddItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItem,
                    request_deserializer=shopping__pb2.AddItemRequest.FromString,
                    response_serializer=shopping__pb2.AddItemResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=shopping__pb2.UpdateItemRequest.FromString,
                    response_serializer=shopping__pb2.OperationResponse.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=shopping__pb2.ItemDeleteRequest.FromString,
                    response_serializer=shopping__pb2.OperationResponse.SerializeToString,
            ),
            'ListItems': grpc.unary_unary_rpc_method_handler(
                    servicer.ListItems,
                    request_deserializer=shopping__pb2.ListItemsRequest.FromString,
                    response_serializer=shopping__pb2.SearchItemsResponse.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=shopping__pb2.SearchItemsRequest.FromString,
                    response_serializer=shopping__pb2.SearchItemsResponse.SerializeToString,
            ),
            'BuyItem': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyItem,
                    request_deserializer=shopping__pb2.BuyItemRequest.FromString,
                    response_serializer=shopping__pb2.OperationResponse.SerializeToString,
            ),
            'AddToWishList': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToWishList,
                    request_deserializer=shopping__pb2.WishListRequest.FromString,
                    response_serializer=shopping__pb2.OperationResponse.SerializeToString,
            ),
            'RateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RateItem,
                    request_deserializer=shopping__pb2.RateItemRequest.FromString,
                    response_serializer=shopping__pb2.OperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shopping.Market', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Market(object):
    """The service definition for the market
    """

    @staticmethod
    def RegisterSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopping.Market/RegisterSeller',
            shopping__pb2.SellerRegisterRequest.SerializeToString,
            shopping__pb2.SellerRegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopping.Market/AddItem',
            shopping__pb2.AddItemRequest.SerializeToString,
            shopping__pb2.AddItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopping.Market/UpdateItem',
            shopping__pb2.UpdateItemRequest.SerializeToString,
            shopping__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopping.Market/DeleteItem',
            shopping__pb2.ItemDeleteRequest.SerializeToString,
            shopping__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopping.Market/ListItems',
            shopping__pb2.ListItemsRequest.SerializeToString,
            shopping__pb2.SearchItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopping.Market/SearchItems',
            shopping__pb2.SearchItemsRequest.SerializeToString,
            shopping__pb2.SearchItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuyItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopping.Market/BuyItem',
            shopping__pb2.BuyItemRequest.SerializeToString,
            shopping__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddToWishList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopping.Market/AddToWishList',
            shopping__pb2.WishListRequest.SerializeToString,
            shopping__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopping.Market/RateItem',
            shopping__pb2.RateItemRequest.SerializeToString,
            shopping__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
